version: '3.6'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - 50035:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tamada-db

  tamada-service:
    build: .
    container_name: tamada-service
    restart: always
    ports:
      - 50040:50040
    volumes:
      - tmd-files-v:/tmd-files

volumes:
  tmd-files-v:
    driver: local
    driver_opts:
      device: /home/pikov_kirya/volumes/tmd-files