version: '3.6'

services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - 50035:5432

  tamada-service:
    build: .
    container_name: tamada-service
    restart: always
    ports:
      - 50040:50040